migrating from HDH repo
ansforge/IG-FHIR-EDS-SOCLE-COMMUN pull request #1
Opened 2024-07-03 09:23 UTC by davidouagne

## Description des changements

* migration du repo HDH vers l'hébergement ANS

## Preview

https://ansforge.github.io/IG-fhir-EDS-SOCLE-COMMUN/main/ig

2024-07-08 07:28 UTC, nriss requested changes
Merci pour ta PR! j'ai fait quelques commentaires mineurs

2024-07-08 07:28 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +* identifier[INS-NIR] ^short = "INS-NIR - The patient national health identifier INS obtained by requesting the national patient identification service (CNAM) called the INSi teleservice. Identifiant
La slice devrait être au niveau du FrCorePatient plutôt qu'au niveau du FrCorePatientINS selon toi ?

2024-07-08 07:28 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +  * ^type.profile = https://interop.esante.gouv.fr/ig/fhir/eds/StructureDefinition/Address
```suggestion
* address only EDSAddress
```

2024-07-08 07:28 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +  * ^type.profile = https://interop.esante.gouv.fr/ig/fhir/eds/StructureDefinition/Address
Il vaut mieux utiliser le nom plutôt que l'URL, ça me paraît plus stable et sera vérifié par le validateur

2024-07-08 07:28 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Address.fsh
> +Profile: Address
```suggestion
Profile: EDSAddress
```

Pour éviter d'avoir le même nom que le datatype officiel Address

2024-07-08 07:28 UTC, nriss commented on input/pagecontent/index.md
> +Le groupe de travail “standards et interopérabilité” lancé en janvier 2024 s’inscrit dans la continuité du précédent
Il y a des sauts de lignes entre les phrases

2024-07-08 07:28 UTC, nriss commented on input/pagecontent/index.md
> +| **Primary Editor** | Prenom Nom |              | prenom.nom@address.email |
Tu peux te mettre en auteur :)

2024-07-08 07:28 UTC, nriss commented on input/pagecontent/index.md
> -    <b>Attention !</b> Cet Implementation Guide n'est pas en version courante. La version courante sera accessible via l'URL canonique suite à la première release : http://interop.esante.gouv.fr/ig/f
Je pense que l'on peut laisser un message pour dire quelque chose comme : 

<b>Attention !</b> Ce guide d'implémentation a été publié pour récolter les commentaires de l'écosystème et gagner en maturité à partir des travaux menés par le HDH. Si ces travaux vous intéressent et que vous souhaitez contribuer, faites en part en issue GitHub ou en faisant directement une Pull Request.

2024-07-08 08:08 UTC, davidouagne commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +* identifier[INS-NIR] ^short = "INS-NIR - The patient national health identifier INS obtained by requesting the national patient identification service (CNAM) called the INSi teleservice. Identifiant
C'est la contrainte de l'obligation du name. Les variables du socle n'ont pas les noms des patients mais propose l'INS. Pour répondre ces exigences j'ai intégré l'INS en copiant depuis FrCorePatientINS. Pas génial comme factorisation à travailler sans doute.

2024-07-08 08:09 UTC, davidouagne commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +  * ^type.profile = https://interop.esante.gouv.fr/ig/fhir/eds/StructureDefinition/Address
Alors, le pb est que ça ne marche pas, c'est un contournement d'une limitation du sushi ;-)

2024-07-08 08:10 UTC, davidouagne commented on input/pagecontent/index.md
> +| **Primary Editor** | Prenom Nom |              | prenom.nom@address.email |
En effet

2024-07-08 08:42 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +* identifier[INS-NIR] ^short = "INS-NIR - The patient national health identifier INS obtained by requesting the national patient identification service (CNAM) called the INSi teleservice. Identifiant
Je prends note pour la prochaine release de FrCore

2024-07-08 08:42 UTC, nriss commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +  * ^type.profile = https://interop.esante.gouv.fr/ig/fhir/eds/StructureDefinition/Address
Je pense que ça ne marchait pas pcq il y avait le même nom de datatype que l'officiel : Address

2024-07-10 14:24 UTC, davidouagne commented on input/fsh/profiles/StructureDefinition-Patient.fsh
> +  * ^type.profile = https://interop.esante.gouv.fr/ig/fhir/eds/StructureDefinition/Address
effectivement !

2024-07-10 15:02 UTC, nriss approved these changes

2024-07-12 05:53 UTC, merged